/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project1;

import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author sandh
 */
public class addcriminal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(addcriminal.class.getName());

    /**
     * Creates new form addcriminal
     */
    public addcriminal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        criminal_id = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        alias = new javax.swing.JTextField();
        dob = new javax.swing.JTextField();
        crimes_involved = new javax.swing.JTextField();
        crime_id = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Criminals");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(565, 6, 333, 56);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Criminal Id");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(373, 113, 146, 28);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(373, 182, 146, 28);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Alias");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(373, 254, 146, 28);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DOB");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(373, 331, 146, 28);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Crimes Involved");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(373, 417, 185, 28);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Crime Id");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(373, 506, 185, 28);

        criminal_id.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(criminal_id);
        criminal_id.setBounds(901, 105, 250, 34);

        name.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(name);
        name.setBounds(901, 174, 250, 34);

        alias.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(alias);
        alias.setBounds(901, 251, 250, 34);

        dob.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobActionPerformed(evt);
            }
        });
        getContentPane().add(dob);
        dob.setBounds(901, 331, 250, 34);

        crimes_involved.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(crimes_involved);
        crimes_involved.setBounds(901, 417, 250, 34);

        crime_id.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        crime_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crime_idActionPerformed(evt);
            }
        });
        getContentPane().add(crime_id);
        crime_id.setBounds(901, 506, 250, 34);

        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(577, 591, 102, 29);

        jButton2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(844, 591, 102, 29);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\sandh\\Downloads\\photo-1530036067142-31e9b88da9b9.jpg")); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 1520, 820);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobActionPerformed

    private void crime_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crime_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crime_idActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Admindashboard a=new Admindashboard();
 a.setVisible(true);
    this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String c= criminal_id.getText();
        System.out.println(c);
        
        String t=name.getText();
        System.out.println(t);
        String d= alias.getText();
        System.out.println(d);
        String l= dob.getText();
        System.out.println(l);
        String de= crimes_involved.getText();
        System.out.println(de);
        String o= crime_id.getText();
        System.out.println(o);
        
        PreparedStatement ps;
        String query = "insert into criminals5(criminal_id,criminal_name,alias,dob,crimes_involved,crime_id)values(?,?,?,?,?,?)";
        try 
        {
            ps=project1.myconnection1.getConnection().prepareStatement(query);
            ps.setString(1,c);
             ps.setString(2,t);
              ps.setString(3,d);
               ps.setString(4,l);
                ps.setString(5,de);
                ps.setString(6,o);
                if(ps.executeUpdate()>0)
                {
                    JOptionPane.showMessageDialog(null, "Criminal details Added completed");
                }
            
        }
        catch(Exception ex){
            System.out.println(ex);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new addcriminal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alias;
    private javax.swing.JTextField crime_id;
    private javax.swing.JTextField crimes_involved;
    private javax.swing.JTextField criminal_id;
    private javax.swing.JTextField dob;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables
}
