/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project1;

import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author sandh
 */
public class addcrime extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(addcrime.class.getName());

    /**
     * Creates new form addcrime
     */
    public addcrime() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        crime_id = new javax.swing.JTextField();
        type = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        location = new javax.swing.JTextField();
        officer_id = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        status = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Add Crimes");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(634, 14, 267, 56);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Crime Id");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(434, 144, 145, 28);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Type");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(434, 214, 145, 28);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Date");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(434, 290, 145, 28);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Location");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(434, 367, 145, 28);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Description");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(434, 439, 145, 28);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(396, 880, 145, 0);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Status");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(434, 577, 145, 28);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Officer Id");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(434, 659, 145, 28);

        crime_id.setBackground(new java.awt.Color(204, 204, 204));
        crime_id.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(crime_id);
        crime_id.setBounds(925, 141, 269, 34);

        type.setBackground(new java.awt.Color(204, 204, 204));
        type.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(type);
        type.setBounds(925, 211, 269, 34);

        date.setBackground(new java.awt.Color(204, 204, 204));
        date.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(date);
        date.setBounds(925, 287, 269, 34);

        description.setBackground(new java.awt.Color(204, 204, 204));
        description.setColumns(20);
        description.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        description.setRows(3);
        description.setTabSize(5);
        jScrollPane1.setViewportView(description);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(925, 439, 269, 90);

        location.setBackground(new java.awt.Color(204, 204, 204));
        location.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(location);
        location.setBounds(925, 367, 269, 34);

        officer_id.setBackground(new java.awt.Color(204, 204, 204));
        officer_id.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        officer_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                officer_idActionPerformed(evt);
            }
        });
        getContentPane().add(officer_id);
        officer_id.setBounds(925, 659, 269, 34);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(618, 731, 115, 29);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(888, 731, 114, 29);

        status.setBackground(new java.awt.Color(204, 204, 204));
        status.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Opened", "Under Investigation", "Closed" }));
        getContentPane().add(status);
        status.setBounds(925, 574, 269, 34);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\sandh\\Downloads\\629065.jpg")); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 1540, 930);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void officer_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_officer_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_officer_idActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Admindashboard a=new Admindashboard();
 a.setVisible(true);
    this.setVisible(false);          // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String c= crime_id.getText();
        System.out.println(c);
        
        String t=type.getText();
        System.out.println(t);
        String d= date.getText();
        System.out.println(d);
        String l= location.getText();
        System.out.println(l);
        String de= description.getText();
        System.out.println(de);
        String a= (String) status.getSelectedItem();
        System.out.println(l);
        String o= officer_id.getText();
        System.out.println(o);
        
       PreparedStatement ps;
String query = "INSERT INTO crimes1(crime_id, type, date, location, description, status, officer_id) VALUES (?, ?, ?, ?, ?, ?, ?)";

try {
    ps = project1.myconnection1.getConnection().prepareStatement(query);

    // Sample variable values (you should ensure these are properly validated)
    int crime_id = Integer.parseInt(c);       // c should be crime_id
    String type = t;                         // t is crime type
    String date = d;                         // d should be in YYYY-MM-DD format
    String location = l;
    String description = de;
    String status = a;
    int officer_id = Integer.parseInt(o);     // o should be an existing officer_id

    // Set parameters
    ps.setInt(1, crime_id);
    ps.setString(2, type);
    ps.setString(3, date);
    ps.setString(4, location);
    ps.setString(5, description);
    ps.setString(6, status);
    ps.setInt(7, officer_id);  // Correctly refer to the officers table using officer_id

    if (ps.executeUpdate() > 0) {
        JOptionPane.showMessageDialog(null, "Crime record added successfully!");
    }

} catch (Exception ex) {
    ex.printStackTrace();
    JOptionPane.showMessageDialog(null, "Error inserting data: " + ex.getMessage());
}   // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new addcrime().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField crime_id;
    private javax.swing.JTextField date;
    private javax.swing.JTextArea description;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField location;
    private javax.swing.JTextField officer_id;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JTextField type;
    // End of variables declaration//GEN-END:variables
}
