/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project1;

import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author sandh
 */
public class assignofficers extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(assignofficers.class.getName());

    /**
     * Creates new form assignofficers
     */
    public assignofficers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        officer_id = new javax.swing.JTextField();
        officername = new javax.swing.JTextField();
        crime_id = new javax.swing.JTextField();
        crimetype = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        criminal_id = new javax.swing.JTextField();
        criminalname = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Assign Officers to Crime");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(464, 6, 583, 56);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Officer Id");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(364, 125, 116, 28);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Officer Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(364, 196, 161, 28);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Crime Id");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(364, 264, 161, 28);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Crime Type");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(364, 336, 161, 28);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(364, 409, 161, 28);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Criminal Id");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(364, 481, 161, 28);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Criminal Name");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(364, 553, 175, 28);

        officer_id.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        officer_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                officer_idActionPerformed(evt);
            }
        });
        getContentPane().add(officer_id);
        officer_id.setBounds(919, 122, 220, 34);

        officername.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(officername);
        officername.setBounds(919, 193, 220, 34);

        crime_id.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        crime_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crime_idActionPerformed(evt);
            }
        });
        getContentPane().add(crime_id);
        crime_id.setBounds(919, 261, 220, 34);

        crimetype.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        crimetype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crimetypeActionPerformed(evt);
            }
        });
        getContentPane().add(crimetype);
        crimetype.setBounds(919, 333, 220, 34);

        date.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(date);
        date.setBounds(919, 406, 220, 34);

        criminal_id.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(criminal_id);
        criminal_id.setBounds(919, 478, 220, 34);

        criminalname.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(criminalname);
        criminalname.setBounds(919, 550, 220, 34);

        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(560, 652, 100, 29);

        jButton2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton2.setText("Assign");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(816, 652, 100, 29);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\sandh\\Downloads\\photo-1530036067142-31e9b88da9b9.jpg")); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 1530, 820);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void officer_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_officer_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_officer_idActionPerformed

    private void crime_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crime_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crime_idActionPerformed

    private void crimetypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crimetypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crimetypeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Admindashboard a=new  Admindashboard();
a.setVisible(true);
this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String c= officer_id.getText();
        System.out.println(c);
        
        String t=officername.getText();
        System.out.println(t);
        String d= crime_id.getText();
        System.out.println(d);
        String l= crimetype.getText();
        System.out.println(l);
        String de= date.getText();
        System.out.println(de);
        String o= criminal_id.getText();
        System.out.println(o);
        String h=criminalname.getText();
        System.out.println(h);
        
        PreparedStatement ps;
        String query = "insert into assignofficer4(officer_id,officer_name,crime_id,type,Date,criminal_id,criminal_name)values(?,?,?,?,?,?,?)";
        try 
        {
            ps=project1.myconnection1.getConnection().prepareStatement(query);
            ps.setString(1,c);
             ps.setString(2,t);
              ps.setString(3,d);
               ps.setString(4,l);
                ps.setString(5,de);
                ps.setString(6,o);
                ps.setString(7,h);
                if(ps.executeUpdate()>0)
                {
                    JOptionPane.showMessageDialog(null, "Assigned officers Successfully");
                }
            
        }
        catch(Exception ex){
            System.out.println(ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new assignofficers().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField crime_id;
    private javax.swing.JTextField crimetype;
    private javax.swing.JTextField criminal_id;
    private javax.swing.JTextField criminalname;
    private javax.swing.JTextField date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField officer_id;
    private javax.swing.JTextField officername;
    // End of variables declaration//GEN-END:variables
}
