/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project1;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author sandh
 */
public class updatecriminals extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(updatecriminals.class.getName());

    /**
     * Creates new form updatecriminals
     */
    public updatecriminals() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dob = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        crime_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        alias = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Criminal_id = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        criminal_id = new javax.swing.JTextField();
        crimes_involved = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        dob.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobActionPerformed(evt);
            }
        });
        getContentPane().add(dob);
        dob.setBounds(855, 469, 300, 34);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Criminal Id");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(381, 238, 146, 28);

        crime_id.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        crime_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crime_idActionPerformed(evt);
            }
        });
        getContentPane().add(crime_id);
        crime_id.setBounds(855, 627, 300, 34);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(381, 312, 146, 28);

        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(529, 721, 102, 29);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Alias");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(381, 386, 146, 28);

        jButton2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(776, 721, 102, 29);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DOB");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(381, 472, 146, 28);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Crimes Involved");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(381, 552, 185, 28);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Crime Id");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(381, 627, 185, 34);

        name.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(855, 309, 300, 34);

        alias.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        alias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aliasActionPerformed(evt);
            }
        });
        getContentPane().add(alias);
        alias.setBounds(855, 383, 300, 34);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Update Criminals");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(541, 0, 414, 56);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Criminal Id");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(381, 107, 146, 28);

        Criminal_id.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(Criminal_id);
        Criminal_id.setBounds(855, 104, 300, 34);

        jButton3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(641, 173, 108, 29);

        criminal_id.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(criminal_id);
        criminal_id.setBounds(855, 235, 300, 34);

        crimes_involved.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(crimes_involved);
        crimes_involved.setBounds(855, 549, 300, 34);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\sandh\\Downloads\\photo-1530036067142-31e9b88da9b9.jpg")); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 1510, 1290);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crime_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crime_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crime_idActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Admindashboard a=new Admindashboard();
 a.setVisible(true);
    this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void aliasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aliasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aliasActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String e=criminal_id.getText();
        String a=name.getText();
        String ad=alias.getText();
        String no=dob.getText();
        String g=crimes_involved.getText();
         String s=crime_id.getText();
        String n=Criminal_id.getText();
 
        
        PreparedStatement ps;
        String query = "update criminals4 Set criminal_id=?,criminal_name=?,alias=?,dob=?,crimes_involved=?,crime_id=? where criminal_id=?";
        try 
        {
            ps=myconnection1.getConnection().prepareStatement(query);
            ps.setString(1,e);
             ps.setString(2,a);
              ps.setString(3,ad);
               ps.setString(4,no);
                ps.setString(5,g);
                 ps.setString(6,s);
                 ps.setString(7,n);
                
                if(ps.executeUpdate()>0)
                {
                    JOptionPane.showMessageDialog(null, "Details Updated");
                }
                else{
                    JOptionPane.showMessageDialog(null, "Details Not Updated");
                }
            
        }
        catch(Exception ex){
            System.out.println(ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
String s=Criminal_id.getText();
        System.out.println(s);
         PreparedStatement ps;
         ResultSet rs;
         try{
             String query="select*from criminals3 where criminal_id=?";
             ps=myconnection1.getConnection().prepareStatement(query);
             ps.setString(1, s);
             rs=ps.executeQuery();
             if(rs.next()){
                 criminal_id.setText(rs.getString(1));
                 name.setText(rs.getString(2));
                 alias.setText(rs.getString(3));
                 dob.setText(rs.getString(4));
                crimes_involved.setText(rs.getString(5));
                 crime_id.setText(rs.getString(6));
             }
             else{
                 JOptionPane.showMessageDialog(null, "Criminal_Id is invalid");
             }
         }
         catch(Exception ex){
             System.out.println(ex);
         }         // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new updatecriminals().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Criminal_id;
    private javax.swing.JTextField alias;
    private javax.swing.JTextField crime_id;
    private javax.swing.JTextField crimes_involved;
    private javax.swing.JTextField criminal_id;
    private javax.swing.JTextField dob;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables
}
