/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project1;

import project1.myconnection1;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


/**
 *
 * @author sandh
 */
public class updatecrime extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(updatecrime.class.getName());

    /**
     * Creates new form updatecrime
     */
    public updatecrime() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        location = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        crime_id = new javax.swing.JTextField();
        status = new javax.swing.JComboBox<>();
        type = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        officer_id = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Crime_id = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Date");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(370, 387, 145, 28);

        location.setBackground(new java.awt.Color(204, 204, 204));
        location.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationActionPerformed(evt);
            }
        });
        getContentPane().add(location);
        location.setBounds(861, 467, 269, 34);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Location");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(370, 470, 145, 28);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Status");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(370, 549, 145, 28);

        crime_id.setBackground(new java.awt.Color(204, 204, 204));
        crime_id.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        crime_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crime_idActionPerformed(evt);
            }
        });
        getContentPane().add(crime_id);
        crime_id.setBounds(861, 218, 269, 34);

        status.setBackground(new java.awt.Color(204, 204, 204));
        status.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Opened", "Under Investigation", "Closed" }));
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        getContentPane().add(status);
        status.setBounds(861, 546, 269, 34);

        type.setBackground(new java.awt.Color(204, 204, 204));
        type.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });
        getContentPane().add(type);
        type.setBounds(861, 300, 269, 34);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Update Crimes");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(580, 6, 338, 56);

        date.setBackground(new java.awt.Color(204, 204, 204));
        date.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(date);
        date.setBounds(861, 384, 269, 34);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Crime Id");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(370, 221, 145, 28);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Type");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(370, 303, 145, 28);

        officer_id.setBackground(new java.awt.Color(204, 204, 204));
        officer_id.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        officer_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                officer_idActionPerformed(evt);
            }
        });
        getContentPane().add(officer_id);
        officer_id.setBounds(861, 630, 269, 34);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Officer Id");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(370, 633, 145, 28);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Crime Id");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(370, 91, 145, 28);

        Crime_id.setBackground(new java.awt.Color(204, 204, 204));
        Crime_id.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(Crime_id);
        Crime_id.setBounds(861, 91, 269, 34);

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(651, 155, 92, 29);

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(552, 698, 100, 29);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(820, 698, 93, 29);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\sandh\\Downloads\\629065.jpg")); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 1560, 830);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void officer_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_officer_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_officer_idActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void locationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionPerformed

    private void crime_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crime_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crime_idActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
Admindashboard a=new Admindashboard();
 a.setVisible(true);
    this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
String s=Crime_id.getText();
        System.out.println(s);
         PreparedStatement ps;
         ResultSet rs;
         try{
             String query="select*from crimes1 where crime_id=?";
             ps=myconnection1.getConnection().prepareStatement(query);
             ps.setString(1, s);
             rs=ps.executeQuery();
             if(rs.next()){
                 crime_id.setText(rs.getString(1));
                 type.setText(rs.getString(2));
                 date.setText(rs.getString(3));
                 location.setText(rs.getString(4));
                status.setSelectedItem(rs.getString(5));
                 officer_id.setText(rs.getString(7));
             }
             else{
                 JOptionPane.showMessageDialog(null, "Crime_Id is invalid");
             }
         }
         catch(Exception ex){
             System.out.println(ex);
         }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String e=crime_id.getText();
        String a=type.getText();
        String ad=date.getText();
        String no=location.getText();
        String s=(String) status.getSelectedItem();
        String g=officer_id.getText();
        String n=Crime_id.getText();
 
        
        PreparedStatement ps;
        String query = "update crimes1 Set crime_id=?,type=?,date=?,location=?,status=?,officer_id=? where crime_id=?";
        try 
        {
            ps=myconnection1.getConnection().prepareStatement(query);
            ps.setString(1,e);
             ps.setString(2,a);
              ps.setString(3,ad);
               ps.setString(4,no);
                ps.setString(5,s);
                ps.setString(6,g);
                 ps.setString(7,n);
                
                if(ps.executeUpdate()>0)
                {
                    JOptionPane.showMessageDialog(null, "Details Updated");
                }
                else{
                    JOptionPane.showMessageDialog(null, "Details Not Updated");
                }
            
        }
        catch(Exception ex){
            System.out.println(ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new updatecrime().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Crime_id;
    private javax.swing.JTextField crime_id;
    private javax.swing.JTextField date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField location;
    private javax.swing.JTextField officer_id;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JTextField type;
    // End of variables declaration//GEN-END:variables
}
