/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project1;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author sandh
 */
public class updateofficers extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(updateofficers.class.getName());

    /**
     * Creates new form updateofficers
     */
    public updateofficers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        officer_id = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        rank = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Officer_id = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(522, 557, 120, 29);

        jButton2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(762, 557, 120, 29);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Officer Id");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(379, 216, 145, 28);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(379, 297, 145, 28);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Rank");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(379, 379, 145, 28);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contact");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(379, 459, 145, 28);

        officer_id.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(officer_id);
        officer_id.setBounds(871, 213, 250, 34);

        name.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(name);
        name.setBounds(871, 294, 250, 34);

        rank.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        rank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rankActionPerformed(evt);
            }
        });
        getContentPane().add(rank);
        rank.setBounds(871, 376, 250, 34);

        contact.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(contact);
        contact.setBounds(871, 456, 250, 34);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Update Officers");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(530, 6, 422, 56);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Officer Id");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(381, 99, 119, 28);

        Officer_id.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(Officer_id);
        Officer_id.setBounds(869, 96, 251, 34);

        jButton3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(652, 148, 100, 29);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\sandh\\Downloads\\dark-and-black-wall-halloween-background-concept-black-concrete-dusty-for-background-horror-cement-texture-free-photo.jpg")); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1510, 810);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rankActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String e=officer_id.getText();
        String a=name.getText();
        String ad=rank.getText();
        String no=contact.getText();
        String g=Officer_id.getText();
        
 
        
        PreparedStatement ps;
        String query = "update officers1 Set officer_id=?,officer_name=?,rank1=?,contact=? where officer_id=?";
        try 
        {
            ps=myconnection1.getConnection().prepareStatement(query);
            ps.setString(1,e);
             ps.setString(2,a);
              ps.setString(3,ad);
               ps.setString(4,no);
                ps.setString(5,g);
               
                
                if(ps.executeUpdate()>0)
                {
                    JOptionPane.showMessageDialog(null, "Details Updated");
                }
                else{
                    JOptionPane.showMessageDialog(null, "Details Not Updated");
                }
            
        }
        catch(Exception ex){
            System.out.println(ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Admindashboard a=new Admindashboard();
 a.setVisible(true);
    this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
String s=Officer_id.getText();
        System.out.println(s);
         PreparedStatement ps;
         ResultSet rs;
         try{
             String query="select*from officers where officer_id=?";
             ps=myconnection1.getConnection().prepareStatement(query);
             ps.setString(1, s);
             rs=ps.executeQuery();
             if(rs.next()){
                 officer_id.setText(rs.getString(1));
                 name.setText(rs.getString(2));
                 rank.setText(rs.getString(3));
                 contact.setText(rs.getString(4));
               
             }
             else{
                 JOptionPane.showMessageDialog(null, "Officer_Id is invalid");
             }
         }
         catch(Exception ex){
             System.out.println(ex);
         }          // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new updateofficers().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Officer_id;
    private javax.swing.JTextField contact;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField name;
    private javax.swing.JTextField officer_id;
    private javax.swing.JTextField rank;
    // End of variables declaration//GEN-END:variables
}
